changelog:
  categories:
    - title: Breaking Changes
      labels:
        - breaking-change
    - title: New Features
      labels:
        - enhancement
        - feature
    - title: Bug Fixes
      labels:
        - bug
        - fix
    - title: Infrastructure
      labels:
        - infrastructure
        - ci
        - docker
    - title: Documentation
      labels:
        - documentation
    - title: Other Changes
      labels:
        - "*"
  exclude:
    labels:
      - skip-changelog
